### ISSUE TITLE
ValueError with numpy > 1.16.4 in README Python example

### ISSUE THREAD

**Issue by sea-shunned** [MLopez-Ibanez/eaf#7]
The example in the README of running ```eaf``` with Python requires ```numpy<=1.16.4``` (and no later, until ```rpy2``` v3.0.x is released and may fix it). Note that this is referenced in another issue for ```rpy2``` ([https://github.com/conda-forge/rpy2-feedstock/issues/28](https://github.com/conda-forge/rpy2-feedstock/issues/28)).

**Comment by MLopez-Ibanez** [comment]
I think this is fixed now. The example works for me.
